## Charger les données

In [5]:
import pandas as pd
from pathlib import Path

bronze_path = Path.cwd().parent / "data" / "bronze" / "parquet"
df_orders_payments = pd.read_parquet (bronze_path/"olist_order_payments_dataset.parquet")


print("Dimensions :", df_orders_payments.shape)

# Vérifier les types et valeurs non nulles
df_orders_payments.info()

df_orders_payments.head(5)

Dimensions : (103886, 5)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103886 entries, 0 to 103885
Data columns (total 5 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   order_id              103886 non-null  object
 1   payment_sequential    103886 non-null  int64
 2   payment_type          103886 non-null  object
 3   payment_installments  103886 non-null  int64
 4   payment_value         103886 non-null  float64
dtypes: float64(1), int64(2), object(2)
memory usage: 4.0+ MB

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45

## Vérification des valeurs négatifs et à zéro

In [6]:

# Vérifier les valeurs négatives
print("Montants négatifs :", (df_orders_payments["payment_value"] < 0).sum())

print("Versements négatifs :", (df_orders_payments["payment_installments"] < 0).sum())

print("Séquences négatives :", (df_orders_payments["payment_sequential"] < 0).sum())

# Vérifier les valeurs à zéro
print("Montants à zéro :", (df_orders_payments["payment_value"] == 0).sum())

print("Versements à zéro :", (df_orders_payments["payment_installments"] == 0).sum())

print("Séquences à zéro :", (df_orders_payments["payment_sequential"] == 0).sum())

Montants négatifs : 0
Versements négatifs : 0
Séquences négatives : 0
Montants à zéro : 9
Versements à zéro : 2
Séquences à zéro : 0

## Examiner les lignes suspectes

In [7]:
# Afficher les paiements dont le montant est égal à zéro
df_orders_payments[df_orders_payments["payment_value"] == 0]

,order_id,payment_sequential,payment_type,payment_installments,payment_value
19922,8bcbe01d44d147f901cd3192671144db,4,voucher,1,0.0
36822,fa65dad1b0e818e3ccc5cb0e39231352,14,voucher,1,0.0
43744,6ccb433e00daae1283ccc956189c82ae,4,voucher,1,0.0
51280,4637ca194b6387e2d538dc89b124b0ee,1,not_defined,1,0.0
57411,00b1cb0320190ca0daa2c88b35206009,1,not_defined,1,0.0
62674,45ed6e85398a87c253db47c2d9f48216,3,voucher,1,0.0
77885,fa65dad1b0e818e3ccc5cb0e39231352,13,voucher,1,0.0
94427,c8c528189310eaa44a745b8d9d26908b,1,not_defined,1,0.0
100766,b23878b3e8eb4d25a158f57d96331b18,4,voucher,1,0.0

In [8]:
#versement à 0`
df_orders_payments[
    df_orders_payments["payment_installments"] == 0
]

,order_id,payment_sequential,payment_type,payment_installments,payment_value
46982,744bade1fcf9ff3f31d860ace076d422,2,credit_card,0,58.69
79014,1a57108394169c0b47d8f876acc9ba2d,2,credit_card,0,129.94

## Vérification des doublons

In [9]:
# Vérifier leslignes entièrement dupliquées

print (df_orders_payments.duplicated().sum())

# Vérifier les doublons sur la clé composée
print("Clé(order_id, payment_sequential ) dupliuée :",
       df_orders_payments.duplicated(
        subset=["order_id", "payment_sequential"]
    ).sum()
      
    )

0
Clé(order_id, payment_sequential ) dupliuée : 0

## Vérifier les types de paiement

In [10]:
# Afficher les différents moyens de paiement
print(df_orders_payments["payment_type"].value_counts())

payment_type
credit_card    76795
boleto         19784
voucher         5775
debit_card      1529
not_defined        3
Name: count, dtype: int64